# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='identifier',
        ),
        migrations.AddField(
            model_name='template',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
