# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20171004_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksegment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracksegment',
            name='provenance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
