# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20171009_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackpoint',
            options={'ordering': ['segment', 'ordinal']},
        ),
        migrations.AddField(
            model_name='tracksegment',
            name='ordinal',
            field=models.IntegerField(default=0),
        ),
    ]
